threads: 8
mem:
  default: 5
  large: 100
runtime:
  default: 5
  minimap: 12
  checkm: 12

fasta_extension: ".fasta" # ['.fasta' '.fasta.gz' is sometimes suported]

sketcher: "bindash" # use bindash or mash for sketching
sketch_k: 21
sketch_size: 10000
sketch_max_dist: 0.2


pre_cluster_threshold: 0.08
subset_size_alignments: 5000
minimap_extra: "-c --secondary=no -x asm20"

fastani:
  k: 16
  minFraction: 0.2
  subset_size: 1000
  extra: ""
bbsketch:
  aa:
    k: "9,12"
  nt:
    k: "31,24"

species_based_on: 'bindash' # bindash, minimap, mummer
strains_based_on: 'minimap'

species_threshold: 0.95 # ]0.9-1[ or 'auto' / auto detects best threshold in range [0.92,0.97]
genome_folder: 'all_bins'
genome_qualities: 'Checkm_quality_allbins.tsv'
quality_score: 'completeness - 5*contamination + 0.5*logN50 + Isolate*100'
qualityfilter_criteria: 'completeness-5*contamination>=50' # use "quality_score" for the above definition
filter_criteria: "N50>5000"
rename_method: "prefix"
mag_prefix: "MAG"

# database_dir: "databases"
