threads: 8

sketcher: "bindash" # use bindash or mash for sketching
sketch_k: 21
sketch_size: 1e4 # 1e3
sketch_max_dist: 0.2

pre_cluster_treshold: 0.1
subset_size_alignments: 500
minimap_extra: "-c --secondary=no -x asm20"

fastani:
  k: 16
  fragLen: 3000
  minFraction: 0.3
  subset_size: 100
bbsketch:
  aa:
    k: "9,12"
  nt:
    k: "31,24"
species_treshold: 'auto' # ]0.9-1[ or 'auto' / auto detects best treshold in range [0.92,0.97]
genome_folder: 'all_bins'
genome_qualities: 'Checkm_quality_allbins.tsv'
quality_score: 'completeness-5*contamination-0.5*strain_heterogeneity'
qualityfilter_criteria: 'quality_score>=50' # use "quality_score" for the above definition
filter_criteria: "N50>5000"
rename_method: "prefix"
mag_prefix: "MAG"

# database_dir: "databases"
