threads: 4
mash:
   k: 21
   sketch_size: 1e4 # 1e3
   max_dist: 0.2
   dist_treshold: 0.1
fastani:
  k: 16
  fragLen: 3000
  minFrag: 50
  subset_size: 1000
genome_folder: 'all_bins'
genome_qualities: 'Checkm_quality_allbins.tsv'
filter_criteria: 'completeness>=50&contamination<=10'
