threads: 8
mash:
   k: 21
   sketch_size: 1e4 # 1e3
   max_dist: 0.2
   dist_treshold: 0.1
fastani:
  k: 16
  fragLen: 3000
  minFrag: 50
  subset_size: 100
genome_folder: 'all_bins'
genome_qualities: 'Checkm_quality_allbins.tsv'
qualityfilter_criteria: '(completeness-5*contamination-0.5*strain_heterogeneity)>=50'
filter_criteria: "N50>5000"
